daemon: true
log:
    displayLevel: 1
    fileLevel: 1
    filePath: /opt/dvm/log
    activityFilePath: /opt/dvm/log
    fileRoot: DVM-CONV1
network:
    enable: true
    id: PEER-ID
    address: 163.123.236.39
    port: 62031
    jitter: 360
    password: "imawhacker6969!"
    slot1: true
    slot2: true
    updateLookups: false
    allowActivityTransfer: true
    allowDiagnosticTransfer: true
    debug: false
    restEnable: false
    restAddress: 0.0.0.0
    restPort: 9990
    restPassword: "imawhacker6969!"
    restDebug: false
protocols:
    p25:
        enable: true
        tduPreambleCount: 6
        control:
            enable: true
            ackRequests: true
            dedicated: false
            broadcast: false
            interval: 300
            duration: 1
            disableTSDUMBF: false
            enableTimeDateAnn: true
        voiceOnControl: false
        disableCompositeFlag: false
        inhibitUnauthorized: false
        legacyGroupGrnt: true
        legacyGroupReg: false
        verifyAff: false
        verifyReg: false
        dumpDataPacket: false
        repeatDataPacket: true
        dumpTsbkData: false
        callHang: 2
        noStatusAck: false
        noMessageAck: true
        unitToUnitAvailCheck: true
        localEmergAlarm: true
        sndcpGrant: false
        silenceThreshold: 124
        disableNetworkHDU: false
        emergDisabled: false
        queueSize: 15
        verbose: true
        debug: false
system:
    identity: SITE ALIAS
    timeout: 180
    duplex: true
    simplexSameFrequency: false
    modeHang: 1
    fixedMode: true
    rfTalkgroupHang: 10
    activeTickDelay: 5
    idleTickDelay: 5
    localTimeOffset: -6
    info:
        latitude: 0
        longitude: 0
        height: 30
        power: 1
        location: "Location, State"
    config:
        authoritative: true
        supervisor: true
        channelId: 0
        channelNo: CHNO
        voiceChNo:
            - channelNo: CHNO
        nac: 69D
        ran: 1
        pSuperGroup: 0100
        announcementGroup: 0100
        netId: 69DEE
        sysId: 69D
        rfssId: 1
        siteId: SITEID
        
    modem:
        protocol:
            type: "uart"
            uart:
                port: /dev/ttyAMA0
                speed: 115200
        rxInvert: false
        txInvert: false
        pttInvert: false
        dcBlocker: true
        cosLockout: false
        fdmaPreamble: 170
        p25CorrCount: 8
        p25FifoLength: 442
        hotspot:
            p25DiscBWAdj: 0
            p25PostBWAdj: 0
            adfGainMode: 0
            afcEnable: false
            afcKI: 11
            afcKP: 4
            afcRange: 1
            txTuning: 0
            rxTuning: 0
        repeater:
            p25SymLvl3Adj: 0
            p25SymLvl1Adj: 0
        softpot:
            rxCoarse: 127
            rxFine: 127
            txCoarse: 127
            txFine: 127
            rssiCoarse: 127
            rssiFine: 127
        rxDCOffset: 0
        txDCOffset: 0
        rxLevel: 50
        txLevel: 50
        rssiMappingFile: RSSI.dat
        packetPlayoutTime: 10
        disableOFlowReset: false
        ignoreModemConfigArea: false
        dumpModemStatus: false
        trace: false
        debug: false
    cwId:
        enable: false
        time: 15
        callsign: WH4CKER
    iden_table:
        file: /opt/dvm/bin/iden_table.dat
        time: 30
    radio_id:
        file: /opt/dvm/bin/rid_acl.dat
        time: 2
        acl: true
    talkgroup_id:
        file: /opt/dvm/bin/tg_acl.yml
        time: 2
        acl: true

